# Generated by Django 2.0.4 on 2020-04-18 11:24

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('cfrom', models.CharField(blank=True, max_length=100, null=True)),
                ('cduration', models.CharField(blank=True, max_length=100, null=True)),
                ('date_called', models.DateTimeField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('ctype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.CharField(blank=True, choices=[('ANDROID', 'ANDROID'), ('IOS', 'IOS')], max_length=30, null=True, verbose_name='platform')),
                ('file_path', models.TextField()),
                ('extract', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('CALLS', 'CALLS'), ('MESSAGES', 'MESSAGES'), ('LOCATION', 'LOCATION')], max_length=30, null=True, verbose_name='extract'), size=None)),
                ('md5', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=100)),
                ('sha512', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_casefile', to='case.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('latlong', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('wifi_mac', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_location', to='case.Case')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=100, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('read', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_message', to='case.Case')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='calllog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_calllog', to='case.Case'),
        ),
        migrations.AlterUniqueTogether(
            name='casefile',
            unique_together={('case', 'platform', 'file_path', 'sha256')},
        ),
    ]
