# Generated by Django 2.0.4 on 2020-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
