# Generated by Django 2.0.4 on 2021-03-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='keph_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
