# Generated by Django 2.0.4 on 2020-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20200418_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
