# Generated by Django 2.0.4 on 2020-05-02 17:48

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_location_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('ts_document', models.TextField(blank=True, help_text='The content that will be searched over', null=True)),
                ('ts_document_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='The ts_vector for the document field', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('neighborhood', models.TextField(blank=True, null=True)),
                ('poi', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('postcode', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_locationdetails', to='case.Location'),
        ),
    ]
