---

- hosts: prod
  user: 'sheriff'
  name:  Nugget
  vars:
    nugget_version: "0.0.1.dev2+464995"
    load_default_data: true
    gunicorn_timeout: 60
    gunicorn_graceful_timeout: 1
    deploy_user: "deploy"
    deploy_group: "deploy"

  pre_tasks:
      - name: create deploy user
        user: name="{{deploy_user}}" groups=www-data,sudo state=present
        become: yes
  roles:
      - common
      - python
      - postgresql
      - nginx
      - supervisor
      - acct
      - letsencrypt
      - logrotate
      - {
          role: "letsencrypt_cert",
          certificate_domain: "api.cislunar.co",
          tags: ["prod_api", "prod_api_cert"]
        }
      - {
          role: "nugget_api",
          name: "nugget_api",
          server_name: "api.cislunar.co",
          allowed_hosts: ".cislunar.co, api.cislunar.co",
          ssl_on: true,
          ssl_cert: "/etc/letsencrypt/live/api.cislunar.co/fullchain.pem",
          ssl_cert_key: "/etc/letsencrypt/live/api.cislunar.co/privkey.pem",
          ssl_trusted_certificate: "/etc/letsencrypt/live/api.cislunar.co/chain.pem",
          tags: ["prod_api"]
        }
